### ISSUE TITLE
Extend ibm_iam_user table to filter user type

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-ibm#14]
**Is your feature request related to a problem? Please describe.**
As per IBM CIS requirement, `1.8 Ensure multi-factor authentication (MFA) is enabled for the account owner`, if we can find the attribute of user type.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/26873346/137704795-5301653b-b406-41bf-b10a-611ea1e6d711.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
user_type is not available in response as of now.
