### ISSUE TITLE
Add table ibm_security_and_compliance

### ISSUE THREAD

**Issue by ManojDhanorkar** [turbot/steampipe-plugin-ibm#91]
https://github.com/IBM/scc-go-sdk/tree/main

**Comment by ParthaI** [comment]
Hello @ManojDhanorkar, I apologize for the delayed response. Thanks for sharing the info about the SDK for IBM security and Compliance.

Using this SDK, we can add multiple tables for Security and Compliance. Such as:
- Profile 
- Attachment
- Control
- ProviderTypeInstance
- ProviderType
- Report
- ReportEvaluation
- ReportResource
- Rule

Could you please let us know which details you want to get? It will help us prioritize the table additions and also will be more clear about the table naming convention.

Thank You!

**Comment by ParthaI** [comment]
Hey @ManojDhanorkar, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
